In [2]:
import pandas as pd
sales = pd.read_excel('https://github.com/datagy/mediumdata/raw/master/pythonexcel.xlsx', sheet_name = 'sales')
states = pd.read_excel('https://github.com/datagy/mediumdata/raw/master/pythonexcel.xlsx', sheet_name = 'states')

# Sales

In [3]:
sales.head()

    Product  Sales       Date           City
0   Bananas    121 2019-06-13        Atlanta
1   Bananas    236 2019-10-20        Atlanta
2    Apples    981 2019-03-12        Atlanta
3     Bread    996 2019-07-28  New York City
4  Brocolli    790 2019-10-22  New York City

# States

In [4]:
states.head()

            City     State
0        Atlanta   Georgia
1  New York City  New York
2        Toronto   Ontario
3       Portland    Oregon

In [5]:
sales['MoreThan500'] = ['Yes' if x > 500 else 'No' for x in sales['Sales']]

In [6]:
sales.head()

    Product  Sales       Date           City MoreThan500
0   Bananas    121 2019-06-13        Atlanta          No
1   Bananas    236 2019-10-20        Atlanta          No
2    Apples    981 2019-03-12        Atlanta         Yes
3     Bread    996 2019-07-28  New York City         Yes
4  Brocolli    790 2019-10-22  New York City         Yes

# Merge

In [7]:
sales = pd.merge(sales, states, how='left', on='City')

In [8]:
sales.head()

    Product  Sales       Date           City MoreThan500     State
0   Bananas    121 2019-06-13        Atlanta          No   Georgia
1   Bananas    236 2019-10-20        Atlanta          No   Georgia
2    Apples    981 2019-03-12        Atlanta         Yes   Georgia
3     Bread    996 2019-07-28  New York City         Yes  New York
4  Brocolli    790 2019-10-22  New York City         Yes  New York

# Pivot Table

In [9]:
sales.pivot_table(index='City', values='Sales', aggfunc='sum')

               Sales
City
Atlanta         7642
New York City   8249
Portland        4231
Toronto         9571

# Color Maps Formatting

In [18]:
sales.style.background_gradient(subset=['Sales'], cmap = 'YlGnBu')

cmap: refers to a color map in Matplotlib. This identifies the type of color scale we want to apply. More details can be found @  https://matplotlib.org/tutorials/colors/colormaps.html

## Data Bars

In [17]:
sales.style.bar(subset=['Sales'], color='#50C878')

## SUMIFs

In [19]:
sales.loc[sales["Product"] == "Bananas", "Sales"].sum()

5843

In [23]:
loc_nyc = sales.loc[sales["City"] == "New York City", "Sales"]
loc_nyc

3     996
4     790
6     870
10    472
17    705
18    710
24    192
25    574
28    587
31    694
43    512
46    904
47    243
Name: Sales, dtype: int64

In [24]:
loc_nyc.sum()

8249